name: arts-n-crafts_rs
services:
  mongodb_rs:
    image: mongo:latest
    container_name: mongodb_rs
    hostname: mongodb_rs
    restart: no
    volumes:
      - mongodb_rs-data:/data/db/
      - mongodb_rs-log:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"

  mongo-express_rs:
    image: mongo-express:latest
    container_name: mongo-express_rs
    # docker compose --profile local up -d
    profiles: [ "local" ]
    restart: no
    environment:
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb_rs
    ports:
      - 8081:8081
    depends_on:
      - mongodb_rs
    deploy:
      replicas: ${MONGO_EXPRESS_REPLICAS:-1}

volumes:
  mongodb_rs-data:
    driver: local
    name: mongo-data_rs
  mongodb_rs-log:
    driver: local
    name: mongo-log_rs
