name: On Push trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify-changes:
    name: Verify changes made
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'arts-n-crafts' }}
    steps:
      - &checkout
        name: 💾 Checkout repository...
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - &install-rust
        name: ⚙️ Install Rust toolchain...
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview, clippy, rustfmt

      - &binstall
        name: 🗄️ Install cargo-binstall...
        run: |
          curl -L https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz \
            | tar -xz -C ~/.cargo/bin

      - &install-test-tools
        name: 🪛 Install nextest test-tool...
        run: |
          cargo binstall --no-confirm cargo-nextest

      - name: 🔨 Install coverage dev-tools...
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: 🔧️ Install audit dev-tools...
        run: |
          cargo binstall --no-confirm cargo-audit

      - name: 🧪 Running tests and code coverage...
        run: cargo llvm-cov nextest --workspace --fail-under-functions 100 --fail-under-lines 100 --fail-under-regions 100

      - name: ☣️ Checking for security vulnerabilities...
        run: RUST_LOG=info cargo audit --quiet

      - name: ✨ Formatting with fmt...
        run: cargo fmt --all -- --check

      - name: 📝 Linting with clippy...
        run: cargo clippy --all-targets --all-features

  test-integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    environment: test
    steps:
      - *checkout
      - *install-rust
      - *binstall
      - *install-test-tools

      - name: 🐳 Initiate Docker services...
        run: docker compose -f docker/mongodb/docker-compose.yaml up -d
        env:
          MONGO_EXPRESS_REPLICAS: 0
          MONGO_INITDB_ROOT_USERNAME: ${{ vars.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ vars.MONGO_INITDB_ROOT_PASSWORD }}

      - name: ⏯️ Wait for Mongo to come online...
        run: |
          echo "Waiting for Mongo (max 3 minutes)..."
          START_TIME=$(date +%s)
          TIMEOUT=180
          while true; do
            if docker exec $(docker ps -qf "name=mongo") mongosh --eval "db.stats()" >/dev/null 2>&1; then
              echo "Mongo is ready ✅"
              break
            fi
            NOW=$(date +%s)
            ELAPSED=$((NOW - START_TIME))
            if [ $ELAPSED -ge $TIMEOUT ]; then
              echo "Mongo did not respond in 3 minutes ❌"
              exit 1
            fi
            sleep 2
          done

      - name: 📈 Test integrations...
        run: cargo nextest run --workspace --retries 2 -- --ignored integration
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ vars.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ vars.MONGO_INITDB_ROOT_PASSWORD }}

      - name: ⏹️ Gracefully shutdown Docker services...
        run: docker compose -f docker/mongodb/docker-compose.yaml down -v
        env:
          MONGO_INITDB_ROOT_USERNAME: ""
          MONGO_INITDB_ROOT_PASSWORD: ""

  release-plz-release:
    name: Release-plz publish
    runs-on: ubuntu-latest
    needs: [verify-changes, test-integration]
    permissions:
      contents: write
    steps:
      - *checkout
      - *install-rust
      - name: 📦 Publish to crates.io...
        uses: release-plz/action@v0.5
        with:
          command: release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    needs: [ verify-changes, test-integration ]
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *checkout
      - *install-rust
      - name: 📤 Create Pull Request...
        uses: release-plz/action@v0.5
        with:
          command: release-pr
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

